export const testingGames: Models.GameInfo[] = [
  {
    name: 'Forza Horizon 4',
    publisher: 'Playground Games',
    background: 'https://gamelegends.it/wp-content/uploads/2021/06/forza-horizon-4-1091.jpeg',
    cover: 'https://criticalhits.com.br/wp-content/uploads/2018/09/forza-horizon-4-cover.jpg',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'The elder scrolls V: Skyrim',
    publisher: 'Bathesda',
    background: 'https://getwallpapers.com/wallpaper/full/7/3/f/62923.jpg',
    cover:
      'https://th.bing.com/th/id/R.b78d05f2dabd5758d9e777e0f22105fb?rik=lEzrCiTm88AZBg&pid=ImgRaw&r=0',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'Follout 4',
    publisher: 'Bathesda',
    background: 'https://images.alphacoders.com/669/669271.jpg',
    cover: 'https://th.bing.com/th/id/OIP.5mnxlc8QM1umk9YuQa5_egHaLH?pid=ImgDet&rs=1',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'Terraria',
    publisher: 'Re-Logic',
    background: 'https://vistapointe.net/images/terraria-6.jpg',
    cover: 'https://monkeycheap.com/wp-content/uploads/2021/04/terraria-cover-600x834.jpg',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
];

export const settingsData: Models.SettingsInfo = {
  bgOption: 'red',
  fullscreen: false,
};
