export const testingGames: AppDB.Models.GameInfo[] = [
  {
    name: 'Forza Horizon 4',
    publisher: 'Playground Games',
    background: 'https://gamelegends.it/wp-content/uploads/2021/06/forza-horizon-4-1091.jpeg',
    cover: 'https://criticalhits.com.br/wp-content/uploads/2018/09/forza-horizon-4-cover.jpg',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'The elder scrolls V: Skyrim',
    publisher: 'Bathesda',
    background: 'https://getwallpapers.com/wallpaper/full/7/3/f/62923.jpg',
    cover:
      'https://th.bing.com/th/id/R.b78d05f2dabd5758d9e777e0f22105fb?rik=lEzrCiTm88AZBg&pid=ImgRaw&r=0',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'Follout 4',
    publisher: 'Bathesda',
    background: 'https://images.alphacoders.com/669/669271.jpg',
    cover: 'https://th.bing.com/th/id/OIP.5mnxlc8QM1umk9YuQa5_egHaLH?pid=ImgDet&rs=1',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'Terraria',
    publisher: 'Re-Logic',
    background: 'https://vistapointe.net/images/terraria-6.jpg',
    cover:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSGmmI6_blJ-tlwVhIhxMUr_YOlkmK0D7Z9Q&s',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'Minecraft',
    publisher: 'Mojang Studios',
    background: 'https://images.alphacoders.com/136/thumb-1920-1360989.jpeg',
    cover: 'https://i.pinimg.com/474x/d2/45/9d/d2459de3246eb8a7d3504903d200f26c.jpg',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
  {
    name: 'Counter-Strike 2',
    publisher: 'Valve',
    background:
      'https://cdn.akamai.steamstatic.com/apps/csgo/images/csgo_react/cs2/maps/dust2_back_plat_s2.jpg',
    cover: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg?t=1693526400',
    addedAt: '',
    description: '',
    hidden: false,
    rate: '',
    year: '',
    gameFile: '',
    gamePath: '',
  },
];

export const settingsData: AppDB.Models.SettingsInfo = {
  bgOption: 'red',
  fullscreen: false,
};
