export const xboxButtonsId: GamepadTypes.GamepadMap = {
  axis0Pos: 'LeftStickRight',
  axis0Neg: 'LeftStickLeft',
  axis1Pos: 'LeftStickDown',
  axis1Neg: 'LeftStickUp',
  axis2Pos: 'RightStickRight',
  axis2Neg: 'RightStickLeft',
  axis3Pos: 'RightStickDown',
  axis3Neg: 'RightStickUp',
  button0: 'ButtonA',
  button1: 'ButtonB',
  button2: 'ButtonX',
  button3: 'ButtonY',
  button4: 'ButtonLeft',
  button5: 'ButtonRight',
  button6: 'TriggerLeft',
  button7: 'TriggerRight',
  button8: 'ButtonSelect',
  button9: 'ButtonStart',
  button10: 'LeftStick',
  button11: 'RightStick',
  button12: 'ArrowUp',
  button13: 'ArrowDown',
  button14: 'ArrowLeft',
  button15: 'ArrowRight',
  button16: 'ButtonHome',
};
