import { IoGameControllerSharp } from 'react-icons/io5';
import {
  RiApps2Fill,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiBatteryFill,
  RiEarthFill,
  RiFile2Line,
  RiFolderFill,
  RiImage2Fill,
  RiLoader5Line,
  RiMovieFill,
  RiMusic2Fill,
  RiNewspaperFill,
  RiPaintBrushFill,
  RiPencilLine,
  RiRemoteControlFill,
  RiSearchLine,
  RiSettings4Fill,
  RiUsbFill,
  RiUser2Fill,
} from 'react-icons/ri';

export const iconMap: Record<App.Props.Icons['type'], React.ReactElement> = {
  games: <IoGameControllerSharp />,
  apps: <RiApps2Fill />,
  music: <RiMusic2Fill />,
  midia: <RiMovieFill />,
  web: <RiEarthFill />,
  news: <RiNewspaperFill />,
  theme: <RiPaintBrushFill />,
  settings: <RiSettings4Fill />,
  user: <RiUser2Fill />,
  battery: <RiBatteryFill />,
  gamepad: <IoGameControllerSharp />,
  search: <RiSearchLine />,
  folder: <RiFolderFill />,
  file: <RiFile2Line />,
  image: <RiImage2Fill />,
  usb: <RiUsbFill />,
  controls: <RiRemoteControlFill />,
  edit: <RiPencilLine />,
  spinner: <RiLoader5Line />,
  'arrow-left': <RiArrowLeftSLine />,
  'arrow-right': <RiArrowRightSLine />,
};
